INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (1, '计算机原理', '操作系统', 'OS and System');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (2, '计算机原理', '计算机网络', 'Internetwork');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (3, '算法书籍', '算法第5版', 'Algorithm 5');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (4, '算法数据', '数据结构与算法', 'Algorithm');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (5, '技术类', 'Spring Boot', 'A1');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (6, '技术类', 'Spring MVC', 'A2');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (7, '数据库', 'MySQL', '关系性数据库');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (8, '数据库', 'Oracle', '关系型数据库');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (9, '测试数据', '123', '123');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (10, '更新数据', '测试数据789', '测试数据789');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (11, '术数类', '梅花易数', '道家推演术数基础');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (12, '添加数据', '789', '789');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (13, '网络开发', 'Web Servlet', 'WS');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (18, '网络开发', 'JavaWeb', 'Web');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (22, '测试数据1', '测试数据2', '测试数据3');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (23, '测试数据1', '测试数据123', '测试数据3');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (24, 'Bug测试', '1234', '1234');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (25, '玄学类', '易经杂说', '周易入门数据');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (29, '科幻类', '三体', '科幻题材');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (30, '测算', '奇门遁甲', '排兵布阵');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (33, '3A游戏', '只狼：影逝二度', '动作、打击类');
INSERT INTO `tb_book` (`id`, `type`, `name`, `description`) VALUES (34, '历史类', '中华上下5000年', '中国编年史');
